# https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slo-reporting.fullname" . }}
  labels:
    {{- include "slo-reporting.labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ date "20060102150405" now }}"
data:
  settings.yaml: |-
{{- with .Values.config }}
    prometheus: {{ .prometheus.url }}
    archive: {{ .bucket.path }}/{{ .bucket.output }}
    slo:
      {{- with .slo }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
{{- end }}
