{{- with .Values.config.metrics.cronjob }}
  {{- if .enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "slo-reporting.fullname" $ }}-update
  labels:
    {{- include "slo-reporting.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "slo-reporting.labels" $ | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: slo-update
              image: curlimages/curl
              command: ['curl']
              args:
                - '-X'
                - 'POST'
                - 'http://{{ include "slo-reporting.fullname" $ }}:{{ $.Values.service.port }}/api/slo/_update'
  {{- end }}
{{- end }}