{{- if .Values.config.metrics.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "slo-reporting.fullname" $ }}-update
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-update
    app.kubernetes.io/instance: {{ .Release.Name }}-update
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Release.Name }}-update
            app.kubernetes.io/instance: {{ .Release.Name }}-update
        spec:
          restartPolicy: Never
          containers:
            - name: slo-update
              image: curlimages/curl
              command: ['curl']
              args:
                - '-X'
                - 'POST'
                - 'http://{{ include "slo-reporting.fullname" $ }}:{{ .Values.service.port }}/api/slo/_update'
{{- end }}
