{{- $fullName := include "slo-reporting.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- range $key, $val := .Values.ingress -}}
{{- if $val.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ $key }}"
  labels:
    {{- include "slo-reporting.labels" $ | nindent 4 }}
  {{- with $val.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $val.className }}
  {{- if $val.tls }}
  tls:
    {{- range $val.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $val.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}