version: "3.7"

x-buildargs: &buildargs
  GIT_COMMIT: ${GIT_COMMIT:-'git-commit'}
  BUILD_VERSION: ${BUILD_VERSION:-'semver'}

services:
  slo-reporting:
    image: ${CR_BASE}/slo-reporting:${BUILD_VERSION:-latest}
    build:
      context: ./src
      args:
        <<: *buildargs
