---
#--------
## Configuration settings
##
config:
  cronjob:
    enabled: true
    # -- The cronjob schedule for running the job (default: nightly at 2AM)
    schedule: "0 23 * * *"
  prometheus:
    url: http://prometheus-community-kube-prometheus.observability:9090
  slo:
    - name: "myservice-uptime"
      display_name: "My Service Uptime"
      goal: 98.0
      rolling_period: 1w
      calendar_period: 30d
      query: 100 * sum(min_over_time(probe_success{instance=~"myservice.+"}[15m])) by (instance)
  bucket:
    # -- Path to the archive file
    output: slo-reporting.csv
    # -- Mount path in pod
    path: /app/data
    # -- Type of bucket to use (azure, gcs, s3)
    type: azure
    # -- Azure File Share to store slo reports
    name: backup
    # -- Name of pre-existing Secret for Azure Storage to use
    secretName: slo-reporting
#--------
image:
  repository: ghcr.io/colenio/slo-reporting
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

resources:
  limits:
    cpu: 10m
    memory: 10Mi
  requests:
    cpu: 10m
    memory: 10Mi
