---
#--------
## Configuration settings
##
config:
  cronjob:
    enabled: true
    # -- The cronjob schedule for running the job (default: nightly at 2AM)
    schedule: "0 23 * * *"
  prometheus:
    # -- Prometheus URL to query
    url: http://prometheus-community-kube-prometheus.observability:9090
  # -- List of SLOs to report on
  slo:
    - name: "prometheus-uptime" # required
      query: 100 * sum(min_over_time(up{job="prometheus"}[15m])) by (job) # promql, required
      goal: 99.9 # 99.9% uptime, default
      rolling_period: P1W # 1 week, default
      step: P1D # 1 day, default
  bucket:
    # -- Path to the archive file
    output: slo-reporting.csv
    # -- Mount path in pod
    path: /app/data
    # -- Type of bucket to use (azure, gcs, s3)
    type: azure
    # -- Azure File Share to store slo reports
    name: backup
    # -- Name of pre-existing Secret for Azure Storage to use
    secretName: slo-reporting
#--------
image:
  repository: ghcr.io/colenio/slo-reporting
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

resources:
  limits:
    cpu: 10m
    memory: 10Mi
  requests:
    cpu: 10m
    memory: 10Mi

# -- Networking
service:
  port: 8000
  type: ClusterIP

ingress:
  enabled: false
  className: "" # nginx
  annotations: {}
  hosts: []
  tls: []

metrics:
  enabled: true
  serviceMonitor: # TODO: document
    # -- Enable a [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec)
    enabled: true
    namespace: ""
    additionalLabels: []
    scrapeInterval: 30s
    honorLabels: false
    relabelings: []
    metricRelabelings: []
    jobLabel: ""
    namespaceSelector: {}
    targetLabels: []
