metrics:
  enabled: True
  prometheus:
    url: http://localhost:9090
  archive: ./data/slo-reporting.csv
  # https://en.wikipedia.org/wiki/ISO_8601#Durations
  window: P1W # P1W, PT1H
  step: P1D # P1D, PT1M
  objectives:
    - name: "prometheus-uptime" # Default prometheus example
      goal: 99.9
      query: 100 * avg(avg_over_time(up{job=~"prometheus.*"}[15m]))
#    - name: "slo" # Pyrra Example
#      goal: 99.9
#      query: 100 * pyrra_objective

status:
  enabled: True
  interval: PT1M
  code: 418 # I'm a teapot on alerts
  monitors:
    azure: []
    #      - name: azure
    #        subscription_id: XXXXXX-XXXX-XXXXXX-XXXX-XXXXXX
    prometheus:
      []
      # - name: prometheus
      #   url: http://localhost:9090
      #   query: 'ALERTS{alertstate="firing", severity="critical", relevance="health-status"}'
    alertmanager:
      - name: alertmanager
        url: http://localhost:9093
        # https://github.com/prometheus/alertmanager/blob/main/api/v2/openapi.yaml
        active: True
        filters:
          - "severity=critical"
          - "relevance=health-status"
        inhibited: False
        receiver: '.*' # (email|slack|webhook)
        silenced: False
        unprocessed: False
