metrics:
  enabled: False # True
  prometheus:
    url: http://localhost:9090
  archive: ./data/slo-reporting.csv
  # https://en.wikipedia.org/wiki/ISO_8601#Durations
  window: P1W # P1W, PT1H
  step: P1D # P1D, PT1M
  objectives:
    - name: "prometheus-uptime"
      goal: 99.9
      query: 100 * sum(min_over_time(up{job="prometheus"}[15m]))
#    - name: "status-uptime"
#      goal: 99.9
#      query: 100 * sum(min_over_time(up{job="prometheus"}[15m]))

status:
  enabled: True
  interval: PT1M
  monitors:
    azure: []
    #      - name: azure
    #        subscription_id: XXXXXX-XXXX-XXXXXX-XXXX-XXXXXX
    prometheus:
      []
      # - name: prometheus
      #   url: http://localhost:9090
      #   query: 'ALERTS{alertstate="firing", severity="critical", relevance="health-status"}'
    alertmanager:
      - name: alertmanager
        url: http://localhost:9093
        filters: []
        #          - "receiver=email"
        #          - "severity=critical"
        #          - "relevance=health-status"
        active: True
        silenced: False
        inhibited: False
        unprocessed: False
