groups:
  - name: slo-reporting
    rules:
      - alert: SloUnderTarget
        expr: sum by (app_id) (azure_app_earliest_expiry{} - time() < 60*24*60*60)
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: SLO under target ({{ $labels.slo }})
          description: "SLO under target \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          dashboard: http://localhost:3000/d/slo-reporting

