name: helm-release

on:
  push:
    branches: [main]
    paths:
      - "charts/**"
  # TODO: For now also enable manual runs
  workflow_dispatch:
  # # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release
  # release:
  #   types:
  #     - prereleased

jobs:
  release:
    runs-on: ubuntu-latest # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
