name: helm-release

on:
  push:
    branches: [main]
    paths: ["charts/**", "!**/*.md"]
  # TODO: For now also enable manual runs
  workflow_dispatch:
  # # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release
  # release:
  #   types:
  #     - prereleased

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Test helm chart
        working-directory: charts/slo-reporting
        run: |
          set -ex
          helm lint .
          if [ -d "charts" ]; then
            helm dependency update
          fi
          if [ -d "tests" ]; then
            helm plugin install https://github.com/helm-unittest/helm-unittest.git
            helm unittest -o tests/TEST-helm.xml -t JUnit .
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
